// SPDX-License-Identifier: Apache-2.0
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { gzipSync } from 'node:zlib';
import { argv } from 'node:process';
import { log } from 'node:console';
import {
  extractFieldFromCompiled,
  computeNormalizedFieldSha256,
} from '../dist/node/index.js';
import {
  createStaticFieldSampler,
  STATIC_MODEL_REVISION,
  STATIC_CLIENT_SHA256,
  STATIC_BUILD_ID,
} from '../dist/index.js';
import { packMapField, unpackMapField } from '../dist/maps.js';

const option = (name) => {
  const i = argv.indexOf(name);
  if (i < 0 || !argv[i + 1]) throw new Error(`missing ${name}`);
  return argv[i + 1];
};
const vpkDir = resolve(option('--vpk-dir')),
  tool = resolve(option('--decompiler')),
  expected = option('--decompiler-sha256');
const work = resolve(option('--work-dir')),
  out = resolve('maps');
const names = [
  'de_ancient',
  'de_anubis',
  'de_cache',
  'de_dust2',
  'de_inferno',
  'de_mirage',
  'de_nuke',
  'de_overpass',
  'de_train',
  'de_vertigo',
];
const hash = (b) => createHash('sha256').update(b).digest('hex');
if (hash(await readFile(tool)) !== expected)
  throw new Error('decompiler-sha256-mismatch');
await mkdir(out, { recursive: true });
const maps = [];
for (const mapName of names) {
  const dir = join(work, mapName);
  await mkdir(dir, { recursive: true });
  const compiledPath = join(dir, 'baked_bomb_damage.vdata_c');
  execFileSync(
    tool,
    [
      '-i',
      join(vpkDir, `${mapName}.vpk`),
      '--vpk_filepath',
      `maps/${mapName}/baked_bomb_damage.vdata_c`,
      '-o',
      compiledPath,
    ],
    { timeout: 120000, stdio: 'pipe' },
  );
  const field = await extractFieldFromCompiled({
    compiledPath,
    decompilerPath: tool,
    decompilerSha256: expected,
    mapName,
    sourceBuildId: STATIC_BUILD_ID,
    sourceClientSha256: STATIC_CLIENT_SHA256,
  });
  const packed = packMapField(field),
    roundtrip = unpackMapField(packed);
  if (
    computeNormalizedFieldSha256(roundtrip) !==
    field.metadata.normalizedFieldSha256
  )
    throw new Error(`lossy-map:${mapName}`);
  const sampler = createStaticFieldSampler(roundtrip);
  for (const site of field.bombsites) {
    const bomb = {
      x: (site.boundsMin.x + site.boundsMax.x) / 2,
      y: (site.boundsMin.y + site.boundsMax.y) / 2,
      z: (site.boundsMin.z + site.boundsMax.z) / 2,
    };
    if (!sampler.lookup(bomb, field.positions[0]).valid)
      throw new Error(`map-query-failed:${mapName}`);
  }
  const bytes = gzipSync(JSON.stringify(packed), { level: 9 });
  const fileName = `${mapName}.json.gz`;
  await writeFile(join(out, fileName), bytes);
  maps.push({
    mapName,
    fileName,
    bytes: bytes.length,
    sha256: hash(bytes),
    positionCount: field.positions.length,
    bombsiteCount: field.bombsites.length,
    resourceSha256: field.metadata.resourceSha256,
    normalizedFieldSha256: field.metadata.normalizedFieldSha256,
  });
  log(`${mapName}: ${field.positions.length} nodes, ${bytes.length} bytes`);
}
const manifest = {
  formatVersion: 1,
  dataRevision: `cs2-${STATIC_BUILD_ID}-v1`,
  modelRevision: STATIC_MODEL_REVISION,
  sourceBuildId: STATIC_BUILD_ID,
  sourceClientSha256: STATIC_CLIENT_SHA256,
  sourceDepot: {
    appId: 730,
    depotId: 2347770,
    manifestId: '2625928478418236338',
  },
  maps,
};
await writeFile(
  join(out, 'manifest.json'),
  JSON.stringify(manifest, null, 2) + '\n',
);
await writeFile(
  'src/maps/catalog.ts',
  '// Generated by scripts/build-maps.mjs. Numerical map data provenance.\nexport const bundledMapManifest = ' +
    JSON.stringify(manifest, null, 2) +
    ' as const;\n',
);
log(`Total: ${maps.reduce((sum, m) => sum + m.bytes, 0)} bytes`);
